### ISSUE TITLE
Allow non-list `Options` arguments

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/packages-plunit#1]
[In `test/2`](https://github.com/SWI-Prolog/packages-plunit/blob/master/plunit.pl#L393) the options list is allowed to be a non-list that is automatically listified.  Should this become a standard feature of specifying options everywhere or is this a plunit-specific feature that I can document?

```prolog
(  is_list(Options0)		% allow for single option without list
->  Options1 = Options0
;   Options1 = [Options0]
),
```

**Comment by JanWielemaker** [comment]
I'm not in favour of that.  In general it is too easy to get ambiguities.
