### ISSUE TITLE
testcase with fixme option and failing assertion generates failed_assertion message

### ISSUE THREAD

**Issue by daniel86** [SWI-Prolog/packages-plunit#6]
Hello,

I am trying to intercept plunit messages to generate a JUnit XML report.
Here is the code I use: https://github.com/daniel86/rosprolog/blob/master/src/rostest.pl#L78

All is working so far except that it seems inconsistent that *failed_assertion* messages are generated when a *fixme* option is used. In case of a failing testcase without assertion, and with fixme option, no *failed* message is generated, so I would expect also no message for failing assertions. How can I find out if there is a fixme note in case only some *failed_assertion* messages are generated for a testcase?
It seems difficult to get the information about which tests are marked with *fixme* in message handlers.

Best,
Daniel

**Comment by JanWielemaker** [comment]
?  Fixme, according to plunit.pl (line 1332) calls

    print_message(informational, plunit(fixme(Failed, Passed, Nondet))).

That is certainly different from assertion failures.   If this doesn't help, please also add an example so I can run it with your code.

**Comment by daniel86** [comment]
Yes I have seen this message, it lacks information about which test case was marked with fixme as it only provides counters.
I will prepare an example in the next days.

**Comment by daniel86** [comment]
here is an example:

```Prolog
:- module(test,[]).

:- begin_tests(test).

test('regular succeed without fixme') :- 
    1 is 1.
test('regular fail without fixme') :-
    1 is 2.
test('regular fail with fixme', [ fixme('foo') ]) :-
    1 is 2.
test('assertion fail without fixme') :-
    assertion(1 is 2).
test('assertion fail with fixme', [ fixme('bar') ]) :-
    assertion(1 is 2).

:- end_tests(test).
```

Running the tests I obtain following output on the console:
```
% PL-Unit: test .
ERROR: /home/danielb/test.pl:7:
	test regular fail without fixme: failed

-
ERROR: /home/danielb/test.pl:11:
	test assertion fail without fixme: assertion failed
	Assertion: 1 is 2
A
ERROR: /home/danielb/test.pl:13:
	test assertion fail with fixme: assertion failed
	Assertion: 1 is 2
+ done
% FIXME: 1 failed; 1 passed
% 2 assertions failed
% 2 tests failed
% 1 tests passed
```

As stated before, the "regular" test cases that do not use assertions will not generate a failure message in case the test fails but is marked with fixme. That is not the case for testcases that use assertions: For such cases, failure message are generated if the testcase fails no matter if there is a fixme option or not.

**Comment by JanWielemaker** [comment]
I now see what you mean.  I have added a new export current_test/5 that allows access to this information from the message handler.  I considered extending the data passed to the handler, but I know more people redefine these messages to produce output compatible to some test framework.  Good we can support all of them :smile: 

This works for me now:

```
prolog:message(plunit(failed_assertion(Unit, Test, Line, AssertLoc,
                                _STO, Reason, Goal))) -->
    { current_test(Unit, Test, Line, _Body, Options),
      option(fixme(Fixme), Options)
    },
    [ 'Assertion in FIXME(~w) test failed'-[Fixme] ].
```

I would be interested in collecting these redefinitions and provide them as part of the distro.  So anyone can do e.g.,

    :- use_module(library(plunit/junit_xml)).

**Comment by daniel86** [comment]
Your suggestion works. I wasn't aware of `current_test`.
Thanks a lot Jan!

I will prepare a module `plunit/junit_xml` in the next days.
